version: '3'

services:
  db:
    container_name: db
    image: mongo
    command: --port 27018
    ports:
      - 27018:27018
    volumes:
      - mongodata:/data/db

  backend:
    container_name: backend
    build: .
    volumes:
      - ./test:/app/test
    ports:
      - 3000:3000
    depends_on:
      - db
    extra_hosts:
      - dashboard.test:127.0.0.1
      - site.test:127.0.0.1
      - site2.test:127.0.0.1
    command: "${TEST_CMD:-npm run test}"
    environment:
      MONGODB_URL: mongodb://db:27018
      MONGODB_PORT: 27018
      NODE_ENV: ${NODE_ENV:-production}
      NODE_APP_INSTANCE: docker

volumes:
  mongodata:
