version: 2.1
jobs:
  build:
    # working_directory: ~/apostrophe-multisite
    docker:
      - image: node:12
      - image: mongo:4.2
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'npm install -g npm@6'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # - run:
      #     name: Install Docker Compose
      #     command: |
      #       curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
      #       chmod +x ~/docker-compose
      #       mv ~/docker-compose /usr/local/bin/docker-compose
      # - setup_remote_docker
      - run:
          name: update host file
          command: |
            echo 127.0.0.1 dashboard.test site.test site2.test | tee -a /etc/hosts
            cat /etc/hosts
      # - run:
      #     name: Start container and verify it is working
      #     command: |
      #       set -x
      #       docker-compose up
      - run:
          name: test
          command: npm test
      - run:
          name: code-coverage
          command: './node_modules/.bin/nyc report --reporter=text-lcov'
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
      - store_test_results:
          path: test-results.xml
